<?php

define('AUTO_ENTITYLABEL_DISABLED', 0);
define('AUTO_ENTITYLABEL_ENABLED', 1);
define('AUTO_ENTITYLABEL_OPTIONAL', 2);
define('AUTO_ENTITYLABEL_PLACEHOLDER', '%AutoEntityLabel%');

/**
 * Implements hook_entity_type_alter().
 */
function auto_entitylabel_entity_type_alter(array &$entity_types) {
  /** @var $entity_types \Drupal\Core\Entity\EntityTypeInterface[] */
  foreach ($entity_types as $entity_type_id => $entity_type) {
    if (($entity_type->getFormClass('default') || $entity_type->getFormClass('edit')) && $entity_type->hasLinkTemplate('edit-form')) {
      $entity_type->setLinkTemplate('auto-label', "/auto-label/$entity_type_id/{{$entity_type_id}}");
    }
  }
}


/**
 * Implements hook_form_alter().
 */
function auto_entitylabel_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {

  if (isset($form['#entity_builders']) && empty($form['#auto_entitylabel_processed'])) {
    $info = $form_state->getFormObject()->getEntity();
    $type = $info->getEntityType()->id();
    $bundle = $info->getType();
    // Exit if there is no label field, e.g. users only have a "label callback"
    $key =  'auto_entitylabel' . '_' . $type . '_type_' . $bundle;
    $title_widget = &$form['title']['widget'][0];
    $form['#auto_entitylabel_processed'] = TRUE;

    // @todo: Port this once title module is released out.
    /**
    // Integration with the title module.
    $replacement = FALSE;

    if (module_exists('title') && (title_field_replacement_enabled($form['#entity_type'], $form['#bundle'], $title))) {
      $title = $info['field replacement'][$title]['instance']['field_name'];
      $replacement = TRUE;
    }
     */
    $auto_entitylabel_config = \Drupal::config('auto_entitylabel.settings');
    $bundle_config = $auto_entitylabel_config->get($key);
    if ($bundle_config == AUTO_ENTITYLABEL_ENABLED) {
      // @todo: Port this once title module is released out.
      /**
      if ($replacement && isset($form[$title])) {
        $form[$title][$form[$title]['#language']][0]['value']['#value'] = AUTO_ENTITYLABEL_PLACEHOLDER;
        $form[$title][$form[$title]['#language']][0]['value']['#type'] = 'value';
        $form[$title][$form[$title]['#language']][0]['value']['#required'] = FALSE;
      }
      else {
       */
      // We will autogenerate the title later, just hide the title field in the
      // meanwhile.
      $title_widget['value']['#default_value'] = AUTO_ENTITYLABEL_PLACEHOLDER;
      $title_widget['value']['#type'] = 'value';
      $title_widget['value']['#required'] = FALSE;
//      }
    }
    elseif ($bundle_config == AUTO_ENTITYLABEL_OPTIONAL) {
      // @todo: Port this once title module is released out.
      /**
      if ($replacement && isset($form[$title])) {
        $form[$title][$form[$title]['#language']][0]['value']['#required'] = FALSE;
      }
      else {
       */
      $title_widget['value']['#required'] = FALSE;
//      }
    }
  }
}
