auto_entitylabel.entity_type.*:
  type: config_entity
  label: 'Auto Entity Label settings'
  mapping:
    status:
      type: integer
      label: 'Status - 0: Disabled, 1: Enabled, 2: Optional'
    pattern:
      type: string
      label: 'Label replacement pattern'
    php:
      type: boolean
      label: 'True if PHP is enabled for replacement'